version: 2
jobs:
  install:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: Install monorepo.
          command: yarn install
  dryrun:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: Perform dryrun on Sync.
          command: yarn sync --dryrun
  sync:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: Perform sync of labels.
          command: yarn sync
workflows:
  version: 2
  sync-labels:
    jobs:
      - install
      - dryrun:
          requires:
            - install
      - hold:
          type: approval
          requires:
            - dryrun
      - sync:
          requires:
            - dryrun
